import express from 'express';
import {excelDocumentos} from './exportar.js';
import path from 'node:path';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {catalogoPublico,disponible,valorar,crear,operar,configurar,editarArticulo,permite,audit} from './servicio.js';
import {publico} from './calculo.js';
import {PDFDocument,StandardFonts} from 'pdf-lib';
export function rutasTienda({store,auth,root,demo=false}) {
 const r=express.Router(), wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
 r.use(express.json({limit:'2mb'}));r.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});
 const visits=new Map();
 r.use((req,res,next)=>{if(req.method==='GET')return next();const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host)return res.status(403).json({error:'Origen no permitido'});}catch{return res.sendStatus(403);}}const key=req.ip,now=Date.now(),v=visits.get(key)||{t:now,n:0};if(now-v.t>60000){v.t=now;v.n=0;}v.n++;visits.set(key,v);if(visits.size>10000)for(const [k,x]of visits)if(now-x.t>60000)visits.delete(k);if(v.n>100)return res.status(429).json({error:'Espera un momento antes de repetir'});next();});
 r.get('/status',wrap(async(req,res)=>{const s=await store.read();res.json({active:s.config.publicActive,demo});}));
 r.get('/catalog',wrap(async(req,res)=>{const s=await store.read();disponible(s);res.json({catalog:catalogoPublico(s),bundles:s.bundles.filter(b=>b.visible&&!b.archived),discounts:s.config.discounts,delivery:s.config.delivery,campaign:s.config.campaign,demo:s.config.demo});}));
 r.post('/calculate',wrap(async(req,res)=>{const s=await store.read();disponible(s);res.json(publico(valorar(s,req.body)));}));
 for(const type of ['orders','quotes'])r.post('/'+type,wrap(async(req,res)=>res.json(await store.mutate(s=>crear(s,req.body,type)))));
 r.use('/admin',auth);
 r.get('/admin/export/:collection(orders|quotes)',wrap(async(req,res)=>{const s=await store.read();if(!permite(s,req.user,'exportar')||!permite(s,req.user,'pedidos'))return res.sendStatus(403);const q=String(req.query.q||'').toLowerCase();const docs=s[req.params.collection].filter(d=>(d.reference+' '+d.contact.company+' '+d.contact.name+' '+d.createdAt+' '+d.campaign+' '+d.payment+' '+d.status).toLowerCase().includes(q));res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('lotes.xlsx').send(excelDocumentos(docs));}));
 r.get('/admin/state',wrap(async(req,res)=>{const s=await store.read();if(!permite(s,req.user,'consultar'))return res.sendStatus(403);const caps=['consultar','catalogo','pedidos','pagos','descuentos','exportar','banco','activar'].filter(c=>permite(s,req.user,c));res.json({config:{...s.config,bank:caps.includes('banco')?s.config.bank:null,permissions:req.user.rol==='direccion'?s.config.permissions:{}},catalog:caps.includes('catalogo')?s.catalog:catalogoPublico(s),bundles:s.bundles,orders:caps.includes('pedidos')?s.orders:[],quotes:caps.includes('pedidos')?s.quotes:[],audit:req.user.rol==='direccion'?s.audit:[],outbox:caps.includes('pedidos')?s.outbox:[],capabilities:caps,demo:s.config.demo});}));
 r.post('/admin/config',wrap(async(req,res)=>res.json(await store.mutate(s=>configurar(s,req.user,req.body)))));
 r.post('/admin/catalog/:id',wrap(async(req,res)=>res.json(await store.mutate(s=>editarArticulo(s,req.user,req.params.id,req.body)))));
 r.post('/admin/:collection(orders|quotes)/:id',wrap(async(req,res)=>res.json(await store.mutate(s=>operar(s,req.user,req.params.collection,req.params.id,req.body)))));
 r.post('/admin/bundles/:id',wrap(async(req,res)=>res.json(await store.mutate(s=>{if(!permite(s,req.user,'catalogo')){const e=new Error('Sin permiso');e.status=403;throw e;}const b=s.bundles.find(b=>b.id===req.params.id);if(!b)throw new Error('Lote no encontrado');if(req.body.lineas)valorar(s,{lineas:req.body.lineas,lotes:1});if(typeof req.body.name==='string')b.name=req.body.name.slice(0,100);if(req.body.lineas)b.lineas=req.body.lineas;if(typeof req.body.visible==='boolean')b.visible=req.body.visible;audit(s,req.user,'editar_lote',b.id);return b;}))));
 r.post('/admin/catalog/:id/image',wrap(async(req,res)=>{const s=await store.read();if(!permite(s,req.user,'catalogo'))return res.sendStatus(403);if(!s.catalog.some(p=>p.id===req.params.id))throw new Error('Artículo no encontrado');const data=req.body.data;if(typeof data!=='string'||data.length>1800000)throw new Error('Imagen demasiado grande');const match=data.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new Error('Usa PNG, JPG o WebP');const buffer=Buffer.from(match[2],'base64');const ok=match[1]==='png'?buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):match[1]==='jpeg'?buffer[0]===255&&buffer[1]===216:buffer.toString('ascii',0,4)==='RIFF'&&buffer.toString('ascii',8,12)==='WEBP';if(!ok)throw new Error('Imagen no válida');res.json(await store.mutate(s=>{if(!permite(s,req.user,'catalogo'))throw new Error('Sin permiso');const p=s.catalog.find(p=>p.id===req.params.id);p.images.unshift({url:data,alt:p.name,source:'Subida por marketing',verified:false});audit(s,req.user,'subir_imagen',p.id);return p;}));}));
 r.get('/admin/:collection(orders|quotes)/:id/pdf',wrap(async(req,res)=>{const s=await store.read();if(!permite(s,req.user,'exportar'))return res.sendStatus(403);const d=s[req.params.collection].find(d=>d.id===req.params.id);if(!d)return res.sendStatus(404);const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage(),y=790;const ca=d.lang==='ca';const line=t=>{const words=String(t).replace(/[^\x20-\xFF]/g,' ').split(/\s+/);let row='';const draw=()=>{if(y<50){page=pdf.addPage();y=790;}page.drawText(row,{x:40,y,size:10,font});y-=19;};for(const word of words){if((row+word).length>90){draw();row='';}row+=(row?' ':'')+word;}draw();};const eur=n=>(n/100).toFixed(2)+' EUR';line('Família de l’Amor - Lots de Nadal');line(d.reference+(d.demo?' - DEMO':''));line(d.contact.name);line(d.contact.company||'');d.snapshot.lineas.forEach(l=>line(`${l.cantidad} x ${l.name[d.lang]} | ${eur(l.netCents)} + IVA ${l.taxBps==null?'?':l.taxBps/100+'%'}`));line((ca?'Base: ':'Base: ')+eur(d.snapshot.baseCents));line((ca?'Descompte: ':'Descuento: ')+eur(d.snapshot.discountCents));line('IVA: '+(d.snapshot.taxCents==null?'pendent / pendiente':eur(d.snapshot.taxCents)));line((ca?'Transport: ':'Transporte: ')+(d.snapshot.transport.pending?'Pendiente':eur(d.snapshot.transport.priceCents+(d.snapshot.transportTaxCents||0))));line((ca?'Total: ':'Total: ')+(d.snapshot.totalCents==null?'pendent / pendiente':eur(d.snapshot.totalCents)));line(d.conditions||'');line(d.notes||'');line(d.dedication||'');line(d.demo?(ca?'DEMOSTRACIÓ. No facis cap pagament.':'DEMOSTRACIÓN. No realices ningún pago.'):'');res.type('pdf').set('Content-Disposition',`attachment; filename="${d.reference}.pdf"`).send(Buffer.from(await pdf.save()));}));
 r.use((e,req,res,next)=>{res.status(e.status||400).json({error:e.message||'No se pudo completar la operación'});});return r;
}
