import test from 'node:test';import assert from 'node:assert/strict';
import {calcular,repartir,publico} from '../../src/modules/tienda/calculo.js';
import {inicial} from '../../src/modules/tienda/catalogo.js';
import {crear,operar,permite,configurar} from '../../src/modules/tienda/servicio.js';
const rules={transport:{pending:false,priceCents:0,taxBps:0}};
function setup(){const s=inicial();s.config.publicActive=true;s.catalog.forEach(p=>p.taxBps=1000);s.config.delivery=[{id:'test',active:true,pending:false,priceCents:0,taxBps:0}];return s;}
function body(){return {key:crypto.randomUUID(),lineas:[{id:'p09',unidades:1},{id:'box-kraft',unidades:1}],lotes:150,deliveryId:'test',contact:{name:'Prueba',email:'test@example.invalid'},accepted:true,lang:'ca'};}
test('Catálogo exacto: sesenta productos y cinco embalajes',()=>{const s=inicial();assert.equal(s.catalog.length,65);assert.deepEqual(Object.values(s.catalog.filter(p=>!p.kind).reduce((a,p)=>(a[p.category]=(a[p.category]||0)+1,a),{})),[8,9,7,12,4,8,8,4]);assert.equal(s.catalog.find(p=>p.id==='p08').priceCents,39990);assert.equal(s.catalog.find(p=>p.id==='box-jamon').priceCents,714);});
for(const [base,bps]of [[49999,0],[50000,500],[99999,500],[100000,1000]])test(`Umbral ${base}: ${bps/100}%`,()=>{const c=[{id:'p',priceCents:base,taxBps:400},{id:'b',kind:'packaging',priceCents:0,taxBps:2100}];const r=calcular(c,{lotes:1,lineas:[{id:'p',unidades:1},{id:'b',unidades:1}]},rules);assert.equal(r.discountBps,bps);});
for(const n of [1,10,100,150,500,501,1000])test(`Compra y presupuesto a ${n} lotes`,()=>{const s=setup(),b={...body(),lotes:n};const a=crear(s,b);const q=crear(s,{...b,key:crypto.randomUUID()},'quotes');assert.equal(s.orders[0].snapshot.lineas[0].cantidad,n);assert.ok(a.reference);assert.ok(q.reference);});
test('Reparto exacto de céntimos e IVA mixto',()=>{assert.deepEqual(repartir(2,[1,1,1]),[1,1,0]);const c=[{id:'a',priceCents:10000,taxBps:400},{id:'b',priceCents:10000,taxBps:1000},{id:'c',priceCents:10000,taxBps:2100},{id:'box',priceCents:0,taxBps:2100,kind:'packaging'}];const r=calcular(c,{lotes:1,lineas:c.map(p=>({id:p.id,unidades:1}))},rules);assert.equal(r.totalCents,33500);assert.equal(r.taxCents,3500);assert.equal(r.lineas.reduce((s,l)=>s+l.taxCents,0),r.taxCents);});
test('No presupone IVA ni transporte cero',()=>{const r=calcular(inicial().catalog,body());assert.equal(r.totalCents,null);assert.equal(r.taxCents,null);});
test('Caja pequeña incompatible con jamón',()=>{assert.throws(()=>calcular(inicial().catalog,{lotes:1,lineas:[{id:'p08',unidades:1},{id:'box-kraft',unidades:1}]}),/compatible/);});
test('Dinero público no expone costes ni margen',()=>{const r=publico(calcular(setup().catalog,body(),rules));assert.equal('costCents'in r,false);assert.equal('costCents'in r.lineas[0],false);});
test('Doble clic no crea dos pedidos ni correos',()=>{const s=setup(),b=body();const a=crear(s,b),c=crear(s,b);assert.equal(a.id,c.id);assert.equal(s.orders.length,1);assert.equal(s.outbox.length,1);assert.equal(s.outbox[0].status,'simulado');});
test('Aviso no confirma pago; permisos e importe exigidos',()=>{const s=setup(),d=crear(s,body()),u={id:1,rol:'direccion'};operar(s,u,'orders',d.id,{action:'reported'});assert.equal(s.orders[0].payment,'pendiente_verificacion');assert.throws(()=>operar(s,{id:2,rol:'marketing'},'orders',d.id,{action:'verify',amountCents:s.orders[0].snapshot.totalCents}),/permiso/);assert.throws(()=>operar(s,u,'orders',d.id,{action:'verify',amountCents:1}),/coincide/);operar(s,u,'orders',d.id,{action:'verify',amountCents:s.orders[0].snapshot.totalCents});assert.equal(s.orders[0].payment,'pagado');});
test('Presupuesto convertido una sola vez e histórico inmutable',()=>{const s=setup(),u={id:1,rol:'direccion'},d=crear(s,body(),'quotes');operar(s,u,'quotes',d.id,{action:'revise',validUntil:'2099-12-31',conditions:'Demo'});operar(s,u,'quotes',d.id,{action:'accept',reason:'Cliente acepta versión 1'});const a=operar(s,u,'quotes',d.id,{action:'convert'}),b=operar(s,u,'quotes',d.id,{action:'convert'});assert.equal(a.id,b.id);assert.equal(s.orders.length,1);const total=a.snapshot.totalCents;s.catalog[8].priceCents=1;assert.equal(s.orders[0].snapshot.totalCents,total);});
for(const publicActive of [true,false])for(const marketingActive of [true,false])test(`Controles independientes ${publicActive}/${marketingActive}`,()=>{const s=setup(),u={id:1,rol:'direccion'};configurar(s,u,{publicActive,marketingActive});assert.equal(s.config.publicActive,publicActive);assert.equal(s.config.marketingActive,marketingActive);assert.equal(permite(s,u,'activar'),true);if(!publicActive)assert.throws(()=>crear(s,body()),/activa/);});
